blank_issues_enabled: false
contact_links:
  - name: General feedback
    url: https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md
    about: Give general feedback about this project
